---
title: "Initial codes"
output:
  pdf_document: default
  html_document: default
---

```{r}
#[1] Read CSV
CapstoneDataSet <- read.csv("{Use public file from UCI machine learning repository}", header = TRUE, sep = ",")
```


```{r}
#[2] To remove ID column from CapstoneDataSet
CapstoneDataSet$ID <- NULL
```

```{r}
#[3] Rename CapstoneDataSet as CS_df
CS_df <- CapstoneDataSet
```

```{r Dataset Structure}
#[4] To view structure of dataset
str(CS_df)
```

```{r}
#[5] Loading the required package
#install.packages("caret")
library(caret)
```




```{r}
#[6] Check zero variance variables
library(caret)
zero_var <- nearZeroVar(CS_df, saveMetrics = TRUE)
zero_var
```



```{r}
#[7] Changing the categorical variables to factor variables:
CS_df[,c(2:4,6:11)] <- lapply(CS_df[,c(2:4,6:11)], factor)
CS_df$DEF_PAY_NEXT_MONTH <- factor(CS_df$DEF_PAY_NEXT_MONTH)
levels(CS_df$DEF_PAY_NEXT_MONTH) <- c("No","Yes")
str(CS_df)
```



```{r}
#[8] Initial Regression
model_LR <- glm(DEF_PAY_NEXT_MONTH ~.,family=binomial(link='logit'),data=CS_df)
summary(model_LR)
```


```{r}
#[9] Attribute Selection using Random Forest
require(randomForest)
fit=randomForest(DEF_PAY_NEXT_MONTH~., data=CS_df)
```



```{r}
#[10] Significant Attribute Selection
library(caret)
varImp(fit)
varImpPlot(fit,type=2)
```


```{r}
#[11] Selecting the Significant Attributes
CS_new <- CS_df[,c(1,2,4,5,12,13,14,15,18,19,24)]
head(CS_new)
```

```{r}
#[12] Divide the dataset into training and test datasets
ind <- createDataPartition(CS_new$DEF_PAY_NEXT_MONTH, p=2/3, list = FALSE)
trainDF <- CS_new[ind, ]
testDF <- CS_new[-ind, ]
```


```{r}
#[13] 10 fold cross validation:
# load the library
library(caret)
# define training control
train_control <- trainControl(method="cv", number=10, verboseIter = T,
                              classProbs = T, sampling = "smote", 
                              summaryFunction = twoClassSummary,
                              savePredictions = T)

```



```{r}
#[14] SVM Model
svmFit <- train(
  DEF_PAY_NEXT_MONTH ~ .,
  data = trainDF,
  method = "svmRadial",
  trControl = train_control,
  metric = "ROC"
)

svmFit
```


```{r}
#[15] Confusion matrix for SVM Model
svm_predict <- predict(svmFit, testDF)
confusionMatrix(svm_predict, testDF$DEF_PAY_NEXT_MONTH)
```



```{r}
#[16] KNN Model
set.seed(3333)
knnFit <- train(
  DEF_PAY_NEXT_MONTH ~ .,
  data = trainDF,
  method = "knn",
  tuneGrid   = expand.grid(k = 1:20),
  trControl = train_control
  
)
knnFit
```


```{r}
#[17] Confusion matrix for KNN Model
knn_predict <- predict(knnFit, testDF)
confusionMatrix(knn_predict, testDF$DEF_PAY_NEXT_MONTH)
```


```{r}
#[18] Neural Network Model
set.seed(6000)
nnFit <- train(
  DEF_PAY_NEXT_MONTH ~ .,
  data = trainDF,
  method = "nnet",
  preProcess=c("scale","center"),
  trControl = train_control
  )
nnFit
```


```{r}
#[19] Confusion Matrix for Neural Netowrk Model
nn_predict <- predict(nnFit, testDF)
confusionMatrix(nn_predict, testDF$DEF_PAY_NEXT_MONTH)
```
